### ISSUE TITLE
Compilation fails with perl >= 5.23.2 (U64 issue)

### ISSUE THREAD

**Issue by eserte** [sanko/digest-xxhash#2]
See subject. Error message is:
```
cc -I. -Isrc -I/opt/perl-5.23.2/lib/5.23.2/x86_64-linux/CORE -DVERSION="1.02" -DXS_VERSION="1.02" -fPIC -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFIL
E_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o lib/Digest/xxHash.o lib/Digest/xxHash.c
lib/Digest/xxHash.xs:114:30: error: conflicting types for 'U64'
In file included from /opt/perl-5.23.2/lib/5.23.2/x86_64-linux/CORE/perl.h:2661:0,
                 from lib/Digest/xxHash.xs:2:
/opt/perl-5.23.2/lib/5.23.2/x86_64-linux/CORE/handy.h:179:17: note: previous declaration of 'U64' was here
error building lib/Digest/xxHash.o from 'lib/Digest/xxHash.c' at /opt/perl-5.23.2/lib/site_perl/5.23.2/ExtUtils/CBuilder/Base.pm line 173.
```

**Comment by eserte** [comment]
Looking at http://fast-matrix.cpantesters.org/?dist=Digest-xxHash%201.02 then things are not that clear. There are PASS reports on Windows and FreeBSD 10.1. Compilation fails on FreeBSD 9.2 and Debian/wheezy. Maybe some compiler issue? FreeBSD 10.1 has clang installed, FreeBSD 9.2 gcc 4.2.1 and Debian/wheezy gcc 4.7.2.

**Comment by sanko** [comment]
I just uploaded 2.00 which (may) resolve 64-bit issues. ...or create entirely new ones since the wrapper now supports upstream's 64-bit hashes; waiting on some test reports to find out which way it'll go.

**Comment by eserte** [comment]
Looks good: http://matrix.cpantesters.org/?dist=Digest-xxHash%202.01
