### ISSUE TITLE
Digest xxHash won't build

### ISSUE THREAD

**Issue by Statue111** [sanko/digest-xxhash#3]
When running ./Build, I received the following messages:

Can't stat ARRAY(0x21d5ae0): No such file or directory
 at /usr/share/perl5/Module/Build/Base.pm line 4288
gcc -I. -IARRAY(0x21d5ae0) -I/usr/lib64/perl5/CORE -DXS_VERSION="2.03" -DVERSION="2.03" -fPIC -c -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -o lib/Digest/xxHash.o lib/Digest/xxHash.c
In file included from lib/Digest/xxHash.xs:5:
./ppport.h:6145:1: warning: "MUTABLE_PTR" redefined
In file included from /usr/lib64/perl5/CORE/perl.h:2424,
                 from lib/Digest/xxHash.xs:2:
/usr/lib64/perl5/CORE/handy.h:63:1: warning: this is the location of the previous definition
lib/Digest/xxHash.xs:22:29: error: perl_math_int64.h: No such file or directory
lib/Digest/xxHash.xs:24:20: error: xxhash.h: No such file or directory
lib/Digest/xxHash.xs: In function 'XS_Digest__xxHash_xxhash32':
lib/Digest/xxHash.xs:33: warning: implicit declaration of function 'XXH32'
lib/Digest/xxHash.xs: In function 'XS_Digest__xxHash_xxhash64':
lib/Digest/xxHash.xs:40: error: 'PERL_MATH_INT64_LOAD' undeclared (first use in this function)
lib/Digest/xxHash.xs:40: error: (Each undeclared identifier is reported only once
lib/Digest/xxHash.xs:40: error: for each function it appears in.)
lib/Digest/xxHash.xs:41: warning: implicit declaration of function 'XXH64'
lib/Digest/xxHash.c:139: warning: implicit declaration of function 'newSVu64'
lib/Digest/xxHash.c:139: warning: assignment makes pointer from integer without a cast
error building lib/Digest/xxHash.o from 'lib/Digest/xxHash.c' at /usr/share/perl5/ExtUtils/CBuilder/Base.pm line 112.

**Comment by sanko** [comment]
Likely a missing or ancient prereq. User was attempting to install Digest::xxHash into system perl v5.10.x without cpan(m).
